#!/usr/bin/env python3
"""
Generates STATUS.md: a single at-a-glance table tying together what
currently lives across three separate places - state/built.json (what
version is currently built, and when, for each tracked package),
packages.txt / large-packages.txt / srcpkgs/ (what's tracked at all,
including things never successfully built yet), and the per-package
GitHub Release for each package (linked, not queried - see below).

No GitHub API calls: state/built.json already stores a "built_at"
timestamp (written by the same workflow step that writes the version),
and a per-package release's tag is always exactly the package name
(assemble_release.sh guarantees this), so its URL can be built directly
without a lookup. This matters because this script runs after every
single package's publish - hitting the Releases API once per *tracked*
package on every *individual* publish would be an O(n^2) cost that
grows silently as packages.txt grows, the same class of problem as the
old unconditional hostdir seed.

Usage:
  python3 scripts/generate_status.py

Env vars:
  REPO or GITHUB_REPOSITORY   "owner/repo" - used only to build release
                              links. Without it, the table still
                              generates, just without links.
  STATUS_OUT                  output path, default STATUS.md.

Wired into CI in the publish job of build-normal.yml / build-large.yml,
right after the step that writes state/built.json - see README.md
"Status page".
"""
import json
import os
import sys
from datetime import datetime, timezone

STATE_PATH = "state/built.json"
OUT_PATH = os.environ.get("STATUS_OUT", "STATUS.md")
REPO = os.environ.get("REPO") or os.environ.get("GITHUB_REPOSITORY")


def read_pkg_list(path):
    if not os.path.exists(path):
        return []
    out = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            out.append(line)
    return out


def fmt_age(iso_ts):
    if not iso_ts:
        return "\u2014"
    try:
        then = datetime.fromisoformat(iso_ts.replace("Z", "+00:00"))
    except ValueError:
        return iso_ts
    days = (datetime.now(timezone.utc) - then).days
    if days <= 0:
        return "today"
    if days == 1:
        return "1 day ago"
    return f"{days} days ago"


def main():
    try:
        with open(STATE_PATH) as f:
            state = json.load(f)
    except FileNotFoundError:
        state = {}

    normal_pkgs = read_pkg_list("packages.txt")
    large_pkgs = read_pkg_list("large-packages.txt")
    custom_pkgs = []
    if os.path.isdir("srcpkgs"):
        custom_pkgs = sorted(
            d for d in os.listdir("srcpkgs")
            if os.path.isfile(os.path.join("srcpkgs", d, "template"))
        )

    all_pkgs = sorted(set(normal_pkgs) | set(large_pkgs) | set(custom_pkgs))

    if not REPO:
        print(
            "  ! REPO / GITHUB_REPOSITORY not set - generating without release links",
            file=sys.stderr,
        )

    rows = []
    built_count = 0
    for pkg in all_pkgs:
        kind = "large" if pkg in large_pkgs else ("custom" if pkg in custom_pkgs else "normal")
        entry = state.get(pkg)
        # Tolerate the older flat-string state format (just "version-revision",
        # no timestamp) as well as the current {"version":..., "built_at":...} dict.
        if isinstance(entry, dict):
            version_rev, built_at = entry.get("version"), entry.get("built_at")
        else:
            version_rev, built_at = entry, None

        if version_rev:
            built_count += 1
        html_url = f"https://github.com/{REPO}/releases/tag/{pkg}" if REPO and version_rev else None
        rows.append((pkg, kind, version_rev or "not built yet", fmt_age(built_at), html_url))

    lines = [
        "<!-- Auto-generated by scripts/generate_status.py - do not edit by hand -->",
        "# Status",
        "",
        f"_Last generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}_",
        "",
        f"{len(all_pkgs)} package(s) tracked, {built_count} currently built.",
        "",
        "| Package | Type | Built version-revision | Last built |",
        "|---|---|---|---|",
    ]
    for pkg, kind, version_rev, last_built, html_url in rows:
        name_cell = f"[`{pkg}`]({html_url})" if html_url else f"`{pkg}`"
        lines.append(f"| {name_cell} | {kind} | {version_rev} | {last_built} |")

    content = "\n".join(lines) + "\n"
    with open(OUT_PATH, "w") as f:
        f.write(content)
    print(f"Wrote {OUT_PATH}: {len(all_pkgs)} packages, {built_count} built", file=sys.stderr)


if __name__ == "__main__":
    main()
